JLLR-41: Feature/rest api
lakovicj/vivify-todo-backend pull request #5
Opened 2020-12-02 13:39 UTC by lakovicj

2020-12-02 14:09 UTC, dejan-stokic requested changes

2020-12-02 14:09 UTC, dejan-stokic commented on todo-backend/app/Models/User.php
> +        return $this->hasMany('App\Models\ToDo');
@lakovicj "Todo" umesto "ToDo".

2020-12-02 14:09 UTC, dejan-stokic commented on todo-backend/app/Http/Controllers/API/TodoController.php
> +        $request->validate([
@lakovicj Custom requests (FormRequest) su super stvar gde mozes definisati validaciju. To bi trebalo uci u praksu. Rasteretice kontroler.

2020-12-02 14:09 UTC, dejan-stokic commented on todo-backend/app/Http/Controllers/API/TodoController.php
> +        $todo = new Todo();
@lakovicj Kontroleri trebaju biti "tanki", sva neka biznis logika treba ici u servise. Time granulisemo odgovornosti i imamo cistiji i reusable kod, lak se bilo kakve dalje promene.

Kreiraj app/Services/TodoService.php i prebaci tamo ovaj deo potreban za priperemu i kreiranje todo-a.

2020-12-02 14:09 UTC, dejan-stokic commented on todo-backend/app/Http/Controllers/API/TodoController.php
> +    public function update(Request $request, Todo $todo)
@lakovicj Isti komentari kao i za store(). Na kraju cemo imati samo par linija koda u odnosu na trenutno.

2020-12-03 01:14 UTC, lakovicj commented on todo-backend/app/Http/Controllers/API/TodoController.php
> +        $request->validate([
Ovo je izmesteno u FormRequests, svi se nalaze u App\Http\Requests.

2020-12-03 01:15 UTC, lakovicj commented on todo-backend/app/Http/Controllers/API/TodoController.php
> +        $todo = new Todo();
Logika je izmestena u App\Services. Servisi su injektovani u konstruktoru kontrolera.

2020-12-04 08:12 UTC, dejan-stokic commented on todo-backend/app/Http/Controllers/API/TodoController.php
> +            $request->merge(array('priority' => strtolower($request->input('priority'))));
@lakovicj Ovo isto moze u servis metodi da se uradi.

2020-12-04 09:16 UTC, merged